name: Crete Doc

on: push
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
      - uses: docker://osusyami/pandoc-jp-pdf:1.0
        with:
          args: README.md -s -o output/resume.docx
      - uses: actions/upload-artifact@master
        with:
          name: resume
          path: output/resume.docx
